# Generated by Django 4.2.6 on 2023-11-05 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='thubnail',
            new_name='thumbnail',
        ),
    ]
